version: "2"
services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        depends_on:
            - mongodata
    mongodata:
        image: tianon/true
        volumes:
            - /data/db
