version: "2"
services:
    webapp:
        build: .
        volumes:
            - ./sslcert:/app/sslcert/
        ports:
            - "8080:8080"
            - "8443:8443"
        links:
            - mongo
        depends_on:
            - mongo
